import Head from "next/head";
import Hero from "@/components/hero";
import Features from "@/components/features";
import FeaturesBlocks from "@/components/features-blocks";
import Testimonials from "@/components/testimonials";
import Newsletter from "@/components/newsletter";
import Header from "@/components/ui/header";
import styled from "styled-components";
import Footer from "@/components/ui/footer";
import "tailwindcss/tailwind.css";

Home.displayName = "Home";
export default function Home() {
  return (
    <>
      <Container className="grow">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <script
            src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"
            async
          ></script>
        </Head>
        <Header />
        <Hero />
        <Features />
        <FeaturesBlocks />
        <Testimonials />
        <Newsletter />
      </Container>
      <Footer />
    </>
  );
}

const Container = styled.div``;
